/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CssTestRouteImport } from './routes/css-test'
import { Route as IndexRouteImport } from './routes/index'

const CssTestRoute = CssTestRouteImport.update({
  id: '/css-test',
  path: '/css-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/css-test': typeof CssTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/css-test': typeof CssTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/css-test': typeof CssTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/css-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/css-test'
  id: '__root__' | '/' | '/css-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CssTestRoute: typeof CssTestRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/css-test': {
      id: '/css-test'
      path: '/css-test'
      fullPath: '/css-test'
      preLoaderRoute: typeof CssTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CssTestRoute: CssTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
