/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CssTestRouteImport } from './routes/css-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GardenNewRouteImport } from './routes/garden/new'
import { Route as ApiPlantsRouteImport } from './routes/api/plants'
import { Route as ApiListingsRouteImport } from './routes/api/listings'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const CssTestRoute = CssTestRouteImport.update({
  id: '/css-test',
  path: '/css-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenNewRoute = GardenNewRouteImport.update({
  id: '/garden/new',
  path: '/garden/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlantsRoute = ApiPlantsRouteImport.update({
  id: '/api/plants',
  path: '/api/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsRoute = ApiListingsRouteImport.update({
  id: '/api/listings',
  path: '/api/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/css-test': typeof CssTestRoute
  '/api/health': typeof ApiHealthRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/plants': typeof ApiPlantsRoute
  '/garden/new': typeof GardenNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/css-test': typeof CssTestRoute
  '/api/health': typeof ApiHealthRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/plants': typeof ApiPlantsRoute
  '/garden/new': typeof GardenNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/css-test': typeof CssTestRoute
  '/api/health': typeof ApiHealthRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/plants': typeof ApiPlantsRoute
  '/garden/new': typeof GardenNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/css-test'
    | '/api/health'
    | '/api/listings'
    | '/api/plants'
    | '/garden/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/css-test'
    | '/api/health'
    | '/api/listings'
    | '/api/plants'
    | '/garden/new'
  id:
    | '__root__'
    | '/'
    | '/css-test'
    | '/api/health'
    | '/api/listings'
    | '/api/plants'
    | '/garden/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CssTestRoute: typeof CssTestRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiListingsRoute: typeof ApiListingsRoute
  ApiPlantsRoute: typeof ApiPlantsRoute
  GardenNewRoute: typeof GardenNewRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/css-test': {
      id: '/css-test'
      path: '/css-test'
      fullPath: '/css-test'
      preLoaderRoute: typeof CssTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden/new': {
      id: '/garden/new'
      path: '/garden/new'
      fullPath: '/garden/new'
      preLoaderRoute: typeof GardenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plants': {
      id: '/api/plants'
      path: '/api/plants'
      fullPath: '/api/plants'
      preLoaderRoute: typeof ApiPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings': {
      id: '/api/listings'
      path: '/api/listings'
      fullPath: '/api/listings'
      preLoaderRoute: typeof ApiListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CssTestRoute: CssTestRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiListingsRoute: ApiListingsRoute,
  ApiPlantsRoute: ApiPlantsRoute,
  GardenNewRoute: GardenNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
