# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'pickmyfruit'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
