# Adapted from https://github.com/marketplace/actions/hashicorp-setup-terraform
name: Deploy

on:
  workflow_call:

jobs:
  www:
    name: www
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          FLY_API_TOKEN=`op read 'op://PickMyFruit/Fly.io/Deploy Token'` \
          flyctl deploy --remote-only --config apps/www/fly.toml --dockerfile apps/www/Dockerfile
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  dns:
    name: DNS
    runs-on: ubuntu-latest
    needs: www
    defaults:
      run:
        working-directory: ./packages/dns
    steps:
      - uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - uses: hashicorp/setup-terraform@v3

      - name: Set Terraform Variables
        run: op inject -i terraform.tfvars.tpl -o terraform.tfvars
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Terraform Init
        run: terraform init

      # TODO: store the plan in the pull request and reuse the plan here
      # to ensure we're deploying exactly what was approved
      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve -backup=- -input=false -var-file="terraform.tfvars"
