# Adapted from https://github.com/marketplace/actions/hashicorp-setup-terraform
name: Deploy

on:
  workflow_call:

env:
  PG_CONN_TYPE: Transaction-Pooler # GitHub Actions doesn't support IPv6

jobs:
  www:
    name: www
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          op run --env-file=packages/env/.env.tpl -- \
          flyctl deploy --remote-only --config apps/www/fly.toml --dockerfile apps/www/Dockerfile
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  dns:
    name: DNS
    runs-on: ubuntu-latest
    needs: www
    defaults:
      run:
        working-directory: ./packages/dns
    steps:
      - uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: ./tf init
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      # TODO: store the plan in the pull request and reuse the plan here
      # to ensure we're deploying exactly what was approved
      - name: Terraform Apply
        run: ./tf apply -no-color -auto-approve -backup=- -input=false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
