# Adapted from https://github.com/marketplace/actions/hashicorp-setup-terraform
name: Deploy

on:
  workflow_call:

jobs:
  www:
    name: www
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config apps/www/fly.toml --dockerfile apps/www/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  dns:
    name: DNS
    runs-on: ubuntu-latest
    needs: www
    defaults:
      run:
        working-directory: ./packages/dns
    steps:
      - uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "TF_VAR_dnsimple_account=${{ secrets.DNSIMPLE_ACCOUNT }}" >> $GITHUB_ENV
          echo "TF_VAR_dnsimple_token=${{ secrets.DNSIMPLE_TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_dnsimple_zone=${{ secrets.DNSIMPLE_ZONE }}" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # TODO: store the plan in the pull request and reuse the plan here
      # to ensure we're deploying exactly what was approved
      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve -backup=- -input=false
