# See https://fly.io/docs/launch/continuous-deployment-with-github-actions/
name: Fly Deploy
on:
  push:
    branches:
      - main # continuous deployment on merge to main

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    secrets: inherit

  deploy:
    uses: ./.github/workflows/_deploy.yaml
    needs: lint
    secrets: inherit
