name: Pull Request

on:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    secrets: inherit

  build:
    uses: ./.github/workflows/_build.yaml
    needs: lint
    secrets: inherit
